runtime: python37
# env: flex
# runtime_config:
#   python_version: 3

env_variables:
  PROJECT_NAME: $GOOGLE_CLOUD_PROJECT
  APP_CONFIG: 'config.py'
  APP_MODULE: 'passwd_studio:application'
  FLASK_DEBUG: 'false'
  FLASK_SECRET: 'secret'
  FLASK_SETTINGS: 'settings.py'
  TIMBER_TOKEN: '123'
  TIMBER_ID: '3457'
  
entrypoint: gunicorn -c $APP_CONFIG -b :$PORT $APP_MODULE

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. 
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#  disk_size_gb: 10

handlers:
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto